<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
            The finally clause works for any exit from try..catch that includes an explicite return

            In the example below, there's a return in try. In this case, finally is executed just before
            the control returns to the outer code
        */

        function func(){
            try{
                return 1;
            } catch(err){
                /*  */
            } finally{
                alert('finally');
            }
        }

        alert(func());
    </script>
</body>
</html>